workers = 2
worker_class = "uvloop"
bind = "0.0.0.0:85"

# Performance Tuning
backlog = 1024 # Maximum number of pending connections
keep_alive_max_requests = 1200 # Maximum number of requests before connection is closed. HTTP/1 & HTTP/2 only.
#max_requests = 1000
max_requests_jitter = 50
loglevel = "WARN"

# cleanup
graceful_timeout = 120 # Time for workers to finish processing i.e SIGTERM or Ctrl-C for any remaining requests (tasks) to complete.
#shutdown_timeout = "5s" 
#keep_alive_timeout = "1s" # How long to keep idle connections