# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/random_city.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'pb/random_city.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14pb/random_city.proto\x12\nrandomcity\" \n\x11RandomCityRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"U\n\x12RandomCityResponse\x12\x15\n\rrandom_cities\x18\x01 \x03(\t\x12\x14\n\x0crandom_state\x18\x02 \x01(\t\x12\x12\n\ntime_taken\x18\x03 \x01(\t2c\n\x11RandomCityService\x12N\n\rGetRandomCity\x12\x1d.randomcity.RandomCityRequest\x1a\x1e.randomcity.RandomCityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.random_city_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANDOMCITYREQUEST']._serialized_start=36
  _globals['_RANDOMCITYREQUEST']._serialized_end=68
  _globals['_RANDOMCITYRESPONSE']._serialized_start=70
  _globals['_RANDOMCITYRESPONSE']._serialized_end=155
  _globals['_RANDOMCITYSERVICE']._serialized_start=157
  _globals['_RANDOMCITYSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
