services:
  app:
    image: ghcr.io/sahiljambhekar/fast-api-playground:worldpop-latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worldpop
    ports:
      - "127.0.0.1:8085:85"
      - "127.0.0.1:8051:50051"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
    environment:
      REDIS_URL: redis://redis:6379/0
      SERVICE_TYPE: http,grpc

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "${HOME}/data/redis/async-await:/data"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #         cpus: '0.1'
volumes:
  redis-data: